package org.ufida;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.15
 * 2017-11-21T15:00:47.856+08:00
 * Generated source version: 3.0.15
 * 
 */
@WebService(targetNamespace = "http://www.UFIDA.org", name = "Homa.U9.Cust.SRMInterfaceSV.ISRMInterServiceSV")
@XmlSeeAlso({org.datacontract.schemas._2004._07.ufsoft_ubf.ObjectFactory.class, org.datacontract.schemas._2004._07.system.ObjectFactory.class, org.datacontract.schemas._2004._07.ufsoft.ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, ObjectFactory.class, exceptions.ubf.ufsoft.ObjectFactory.class, org.datacontract.schemas._2004._07.ufsoft_ubf_util.ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class})
public interface HomaU9CustSRMInterfaceSVISRMInterServiceSV {

    @Action(input = "http://www.UFIDA.org/Homa.U9.Cust.SRMInterfaceSV.ISRMInterServiceSV/Do", output = "http://www.UFIDA.org/Homa.U9.Cust.SRMInterfaceSV.ISRMInterServiceSV/DoResponse", fault = {@FaultAction(className = HomaU9CustSRMInterfaceSVISRMInterServiceSVDoServiceExceptionFaultFaultMessage.class, value = "http://www.UFIDA.org/Homa.U9.Cust.SRMInterfaceSV.ISRMInterServiceSV/DoServiceExceptionFault"), @FaultAction(className = HomaU9CustSRMInterfaceSVISRMInterServiceSVDoExceptionFaultFaultMessage.class, value = "http://www.UFIDA.org/Homa.U9.Cust.SRMInterfaceSV.ISRMInterServiceSV/DoExceptionFault"), @FaultAction(className = HomaU9CustSRMInterfaceSVISRMInterServiceSVDoServiceLostExceptionFaultFaultMessage.class, value = "http://www.UFIDA.org/Homa.U9.Cust.SRMInterfaceSV.ISRMInterServiceSV/DoServiceLostExceptionFault"), @FaultAction(className = HomaU9CustSRMInterfaceSVISRMInterServiceSVDoExceptionBaseFaultFaultMessage.class, value = "http://www.UFIDA.org/Homa.U9.Cust.SRMInterfaceSV.ISRMInterServiceSV/DoExceptionBaseFault"), @FaultAction(className = HomaU9CustSRMInterfaceSVISRMInterServiceSVDoServiceExceptionDetailFaultFaultMessage.class, value = "http://www.UFIDA.org/Homa.U9.Cust.SRMInterfaceSV.ISRMInterServiceSV/DoServiceExceptionDetailFault")})
    @RequestWrapper(localName = "Do", targetNamespace = "http://www.UFIDA.org", className = "org.ufida.Do")
    @WebMethod(operationName = "Do", action = "http://www.UFIDA.org/Homa.U9.Cust.SRMInterfaceSV.ISRMInterServiceSV/Do")
    @ResponseWrapper(localName = "DoResponse", targetNamespace = "http://www.UFIDA.org", className = "org.ufida.DoResponse")
    public void _do(
        @WebParam(name = "context", targetNamespace = "http://www.UFIDA.org")
        java.lang.Object context,
        @WebParam(name = "jsonStr", targetNamespace = "http://www.UFIDA.org")
        java.lang.String jsonStr,
        @WebParam(name = "transCode", targetNamespace = "http://www.UFIDA.org")
        java.lang.String transCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "DoResult", targetNamespace = "http://www.UFIDA.org")
        javax.xml.ws.Holder<java.lang.String> doResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "outMessages", targetNamespace = "http://www.UFIDA.org")
        javax.xml.ws.Holder<exceptions.ubf.ufsoft.ArrayOfMessageBase> outMessages
    ) throws HomaU9CustSRMInterfaceSVISRMInterServiceSVDoServiceExceptionFaultFaultMessage, HomaU9CustSRMInterfaceSVISRMInterServiceSVDoExceptionFaultFaultMessage, HomaU9CustSRMInterfaceSVISRMInterServiceSVDoServiceLostExceptionFaultFaultMessage, HomaU9CustSRMInterfaceSVISRMInterServiceSVDoExceptionBaseFaultFaultMessage, HomaU9CustSRMInterfaceSVISRMInterServiceSVDoServiceExceptionDetailFaultFaultMessage;
}
