
package org.ufida;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.15
 * 2017-11-21T15:00:47.844+08:00
 * Generated source version: 3.0.15
 */

@WebFault(name = "ExceptionBase", targetNamespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF")
public class HomaU9CustSRMInterfaceSVISRMInterServiceSVDoExceptionBaseFaultFaultMessage extends java.lang.Exception {
    
    private org.datacontract.schemas._2004._07.ufsoft.ExceptionBase exceptionBase;

    public HomaU9CustSRMInterfaceSVISRMInterServiceSVDoExceptionBaseFaultFaultMessage() {
        super();
    }
    
    public HomaU9CustSRMInterfaceSVISRMInterServiceSVDoExceptionBaseFaultFaultMessage(String message) {
        super(message);
    }
    
    public HomaU9CustSRMInterfaceSVISRMInterServiceSVDoExceptionBaseFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public HomaU9CustSRMInterfaceSVISRMInterServiceSVDoExceptionBaseFaultFaultMessage(String message, org.datacontract.schemas._2004._07.ufsoft.ExceptionBase exceptionBase) {
        super(message);
        this.exceptionBase = exceptionBase;
    }

    public HomaU9CustSRMInterfaceSVISRMInterServiceSVDoExceptionBaseFaultFaultMessage(String message, org.datacontract.schemas._2004._07.ufsoft.ExceptionBase exceptionBase, Throwable cause) {
        super(message, cause);
        this.exceptionBase = exceptionBase;
    }

    public org.datacontract.schemas._2004._07.ufsoft.ExceptionBase getFaultInfo() {
        return this.exceptionBase;
    }
}
