
package org.ufida;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.15
 * 2017-11-21T15:00:47.850+08:00
 * Generated source version: 3.0.15
 */

@WebFault(name = "ServiceExceptionDetail", targetNamespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF.Service")
public class HomaU9CustSRMInterfaceSVISRMInterServiceSVDoServiceExceptionDetailFaultFaultMessage extends java.lang.Exception {
    
    private org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceExceptionDetail serviceExceptionDetail;

    public HomaU9CustSRMInterfaceSVISRMInterServiceSVDoServiceExceptionDetailFaultFaultMessage() {
        super();
    }
    
    public HomaU9CustSRMInterfaceSVISRMInterServiceSVDoServiceExceptionDetailFaultFaultMessage(String message) {
        super(message);
    }
    
    public HomaU9CustSRMInterfaceSVISRMInterServiceSVDoServiceExceptionDetailFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public HomaU9CustSRMInterfaceSVISRMInterServiceSVDoServiceExceptionDetailFaultFaultMessage(String message, org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceExceptionDetail serviceExceptionDetail) {
        super(message);
        this.serviceExceptionDetail = serviceExceptionDetail;
    }

    public HomaU9CustSRMInterfaceSVISRMInterServiceSVDoServiceExceptionDetailFaultFaultMessage(String message, org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceExceptionDetail serviceExceptionDetail, Throwable cause) {
        super(message, cause);
        this.serviceExceptionDetail = serviceExceptionDetail;
    }

    public org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceExceptionDetail getFaultInfo() {
        return this.serviceExceptionDetail;
    }
}
