
package org.ufida;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.15
 * 2017-11-21T15:00:47.837+08:00
 * Generated source version: 3.0.15
 */

@WebFault(name = "ServiceLostException", targetNamespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF.Service")
public class HomaU9CustSRMInterfaceSVISRMInterServiceSVDoServiceLostExceptionFaultFaultMessage extends java.lang.Exception {
    
    private org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceLostException serviceLostException;

    public HomaU9CustSRMInterfaceSVISRMInterServiceSVDoServiceLostExceptionFaultFaultMessage() {
        super();
    }
    
    public HomaU9CustSRMInterfaceSVISRMInterServiceSVDoServiceLostExceptionFaultFaultMessage(String message) {
        super(message);
    }
    
    public HomaU9CustSRMInterfaceSVISRMInterServiceSVDoServiceLostExceptionFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public HomaU9CustSRMInterfaceSVISRMInterServiceSVDoServiceLostExceptionFaultFaultMessage(String message, org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceLostException serviceLostException) {
        super(message);
        this.serviceLostException = serviceLostException;
    }

    public HomaU9CustSRMInterfaceSVISRMInterServiceSVDoServiceLostExceptionFaultFaultMessage(String message, org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceLostException serviceLostException, Throwable cause) {
        super(message, cause);
        this.serviceLostException = serviceLostException;
    }

    public org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceLostException getFaultInfo() {
        return this.serviceLostException;
    }
}
