
package org.ufida;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.15
 * 2017-11-21T15:00:47.804+08:00
 * Generated source version: 3.0.15
 */

@WebFault(name = "ServiceException", targetNamespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF.Service")
public class HomaU9CustSRMInterfaceSVISRMInterServiceSVDoServiceExceptionFaultFaultMessage extends java.lang.Exception {
    
    private org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceException serviceException;

    public HomaU9CustSRMInterfaceSVISRMInterServiceSVDoServiceExceptionFaultFaultMessage() {
        super();
    }
    
    public HomaU9CustSRMInterfaceSVISRMInterServiceSVDoServiceExceptionFaultFaultMessage(String message) {
        super(message);
    }
    
    public HomaU9CustSRMInterfaceSVISRMInterServiceSVDoServiceExceptionFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public HomaU9CustSRMInterfaceSVISRMInterServiceSVDoServiceExceptionFaultFaultMessage(String message, org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceException serviceException) {
        super(message);
        this.serviceException = serviceException;
    }

    public HomaU9CustSRMInterfaceSVISRMInterServiceSVDoServiceExceptionFaultFaultMessage(String message, org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceException serviceException, Throwable cause) {
        super(message, cause);
        this.serviceException = serviceException;
    }

    public org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceException getFaultInfo() {
        return this.serviceException;
    }
}
