
package saaf.common.fmw.base.ws.ekp;

import saaf.common.fmw.base.ws.process.SyncProcess;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IKmReviewWebserviceServiceService", targetNamespace = "http://webservice.review.km.kmss.landray.com/", wsdlLocation = "http://10.10.1.198:8080/ekp/sys/webservice/kmReviewWebserviceService?wsdl")
public class IKmReviewWebserviceServiceService
    extends Service
{

    private final static URL IKMREVIEWWEBSERVICESERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException IKMREVIEWWEBSERVICESERVICESERVICE_EXCEPTION;
    private final static QName IKMREVIEWWEBSERVICESERVICESERVICE_QNAME = new QName("http://webservice.review.km.kmss.landray.com/", "IKmReviewWebserviceServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            String ekpURL = SyncProcess.PRO.getProperty("ekpURL");
            String ekpStartURL = SyncProcess.PRO.getProperty("ekpStartURL");
            url = new URL(ekpURL+ekpStartURL);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IKMREVIEWWEBSERVICESERVICESERVICE_WSDL_LOCATION = url;
        IKMREVIEWWEBSERVICESERVICESERVICE_EXCEPTION = e;
    }

    public IKmReviewWebserviceServiceService() {
        super(__getWsdlLocation(), IKMREVIEWWEBSERVICESERVICESERVICE_QNAME);
    }

    public IKmReviewWebserviceServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IKMREVIEWWEBSERVICESERVICESERVICE_QNAME, features);
    }

    public IKmReviewWebserviceServiceService(URL wsdlLocation) {
        super(wsdlLocation, IKMREVIEWWEBSERVICESERVICESERVICE_QNAME);
    }

    public IKmReviewWebserviceServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IKMREVIEWWEBSERVICESERVICESERVICE_QNAME, features);
    }

    public IKmReviewWebserviceServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IKmReviewWebserviceServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IKmReviewWebserviceService
     */
    @WebEndpoint(name = "IKmReviewWebserviceServicePort")
    public IKmReviewWebserviceService getIKmReviewWebserviceServicePort() {
        return super.getPort(new QName("http://webservice.review.km.kmss.landray.com/", "IKmReviewWebserviceServicePort"), IKmReviewWebserviceService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IKmReviewWebserviceService
     */
    @WebEndpoint(name = "IKmReviewWebserviceServicePort")
    public IKmReviewWebserviceService getIKmReviewWebserviceServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.review.km.kmss.landray.com/", "IKmReviewWebserviceServicePort"), IKmReviewWebserviceService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IKMREVIEWWEBSERVICESERVICESERVICE_EXCEPTION!= null) {
            throw IKMREVIEWWEBSERVICESERVICESERVICE_EXCEPTION;
        }
        return IKMREVIEWWEBSERVICESERVICESERVICE_WSDL_LOCATION;
    }

}
